import { NAMESPACE_COMMON } from '../../../consts';

export const COMMON_LOADING_OPEN = `${NAMESPACE_COMMON}/COMMON_LOADING_OPEN`;
export const COMMON_LOADING_CLOSE = `${NAMESPACE_COMMON}/COMMON_LOADING_CLOSE`;
