import { NAMESPACE_NEWS } from '../../consts';

export const SET_NEWS_FILTER = `${NAMESPACE_NEWS}/SET_NEWS_FILTER`;
export const SET_NEWS_FILTER_TOTAL_PAGE = `${NAMESPACE_NEWS}/SET_NEWS_FILTER_TOTAL_PAGE`;

export const GET_NEWS = `${NAMESPACE_NEWS}/GET_NEWS`;
export const SET_NEWS = `${NAMESPACE_NEWS}/SET_NEWS`;
export const SET_NEWS_ERROR = `${NAMESPACE_NEWS}/SET_NEWS_ERROR`;

export const GET_BLOGS = `${NAMESPACE_NEWS}/GET_BLOGS`;
export const SET_BLOGS = `${NAMESPACE_NEWS}/SET_BLOGS`;
export const SET_BLOGS_ERROR = `${NAMESPACE_NEWS}/SET_BLOGS_ERROR`;
