import { NAMESPACE_HOME } from '../../consts';

export const REQUEST_EMAIL = `${NAMESPACE_HOME}/REQUEST_EMAIL`;
export const REQUEST_EMAIL_SUCCESS = `${NAMESPACE_HOME}/REQUEST_EMAIL_SUCCESS`;
export const REQUEST_EMAIL_ERROR = `${NAMESPACE_HOME}/REQUEST_EMAIL_ERROR`;
export const MODAL_MESS_CLOSE = `${NAMESPACE_HOME}/MODAL_MESS_CLOSE`;
